name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-inspire:
    runs-on: ubuntu-latest
    services:
      inspire:
        image: pdokdev/inspire-validator:test
        ports: 
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: Check status of inspire validator
        # Dit zal wel niet werken omdat de service er even over doet om op te starten
        run: |
          ls $GITHUB_WORKSPACE
          curl -X GET --header 'Accept: application/json' 'localhost:8080/validator/v2/status'
